name: 存档视频

on:
  issues:
    types: [opened, edited]
    
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@v3
        
      - name: 安装 ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
            
      - name: 下载视频
        run: |
          mkdir output
          cd output
          python3 ../archiver.py
        
      - name: 上传
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'peasoft'
          destination-repository-name: 'ArchiveRepo'
          user-email: luliucheng100@outlook.com
          target-branch: master
