name: 存档视频

on:
  issues:
    types: [opened]
    
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: 安装 requests
        run: python -m pip install requests
        
      - name: 安装 ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
            
      - name: 下载视频
        run: |
          mkdir output
          cd output
          python3 ../archiver.py
        
      - name: 上传
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: |
            output/
